### ISSUE TITLE
README request

### ISSUE THREAD

**Issue by arbabnazar** [linuxdynasty/ld-ansible-filters#1]
@linuxdynasty can you please add some example to the README that how we can use it. Thanks

**Comment by linuxdynasty** [comment]
Sure thing

**Comment by arbabnazar** [comment]
Hope to see it really soon

**Comment by linuxdynasty** [comment]
I just blogged about it here http://linuxdynasty.github.io/Linuxdynasty/ansible-filters-and-how-they-can-make-aws-your-playbooks-dynamic/

**Comment by linuxdynasty** [comment]
I will still add some examples to the README as well

**Comment by arbabnazar** [comment]
Thanks @linuxdynasty for this writing.

**Comment by linuxdynasty** [comment]
@arbabnazar I added a decorator for all of the aws calls today. This is great, since Amazon throttles the requests.

**Comment by arbabnazar** [comment]
@linuxdynasty I saw your presentation at Ansiblefest2016 today. Bundle of thanks for this as well as for the presentation. So this is not enough :-) We want one blog post/wiki against your Ansiblefest presentation so that we can use it as reference while building our AWS infrastructure. Thanks
