### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by geekq** [linuxdynasty/ld-ansible-filters#3]
Thanks @linuxdynasty for

1. inspiration to use ansible filters to access needed data from AWS
2. collection of filters ready to use

The project does not provide a license though, making it hard to use in an enterprise-y environment or to include/use it in own open source projects.

Could you please add a license file, ideally MIT, like https://github.com/Galeria-Kaufhof/private-postgres-rds/blob/master/LICENSE.txt or just use github UI to add https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by linuxdynasty** [comment]
Sure thing and thank you for the compliments.

**Comment by linuxdynasty** [comment]
Done.
